### PR TITLE
Design changes

### PR DESCRIPTION
**Pull request by jezsmith720**
Alterations to layout/design of homepage.
See visual representation @ screenshots below;
Desktop/Large - https://ibb.co/brSRZtg
Tablet/Medium - https://ibb.co/cxt9rzF
Mobile/Small - https://ibb.co/pzXwyVs
(Using Bootstrap for grid system/layout)
Let me know about any required changes or additions needed :).
Thank you for the opportunity and apologies again regarding delays.

### CODE REVIEW

**Comment by abbey-titcomb** [comment]
Hey ! Great work - definitely in the right direction. Had a couple of comments to share so tried to markup a screenshot to communicate them.

Overall, let's stick with the structure and just make some stylistic changes to make it a bit more symmetric / minimal. But I love the side bar navigation and speaker list - really unique and cool. 

Let me know if you want more color on the comments! I have time tomorrow to provide more thoughts

sustainweb3comments

**Comment by owocki** [comment]
my edits:
- make the logo smaller.. less than 200px x 200px
- move the speakers onto their own row

**Comment by jezsmith720** [comment]
Cool no prob, thanks for the comments, i'll be working on this tonight :)

**Comment by jezsmith720** [comment]
I've done the stated changes and pushed them to my forks master branch, do I need to create another PR or is everything still accessible from here?
Could you please confirm the correct links for the sponsors (can't find through google image search). 
Also due to reducing logo size, I kept the Location/Date on separate lines to avoid too much whitespace and for easier mobile readability. I have added another icon for coordinators section, let me know if it is appropriate. Thanks

**Comment by owocki** [comment]
were having a web3 sustain event sstandup tomorrow at 830 am MST. @jezsmith720   @abbey-titcomb any way we can get the site updated with the latest in this PR by then?  would love to start moving towards a site that can be the canonical source of truth for the event soon

**Comment by abbey-titcomb** [comment]
Sure sure. I'll review and merge and redeploy!

**Review by abbey-titcomb — APPROVED** [review]
Looks great! The structural changes and design direction were exactly what we were looking for. Appreciate it!!

**Comment by jezsmith720** [comment]
Cool, let me know of any additions :)

**Pull request merged**
