### PR TITLE
small cleanup

### PR DESCRIPTION
**Pull request by jezsmith720**

### CODE REVIEW

**Comment by abbey-titcomb** [comment]
merged! Thanks !!

**Comment by jezsmith720** [comment]
Awesome - If things aren't working properly since latest merge. 

Some changes I made in the first place to get my dev env up and running that also may affect building/compilation in your environment.

1.   In package.json, I changed **"dev": "NODE_PATH=. next",**  to **"dev": "next",** 
2.   All imports changed from e.g. **import Nav from 'components/Nav';** to **import Nav from '../components/Nav';**
3.   Node module packages in package-lock.json have been updated.

**Comment by xla** [comment]
> * In package.json, I changed **"dev": "NODE_PATH=. next",**  to **"dev": "next",**
> 
> * All imports changed from e.g. **import Nav from 'components/Nav';** to **import Nav from '../components/Nav';**

@jezsmith720 Why the removal of absolute imports?

**Comment by jezsmith720** [comment]
@xla for some reason I couldn't get a dev instance of the site running until I changed the absolute paths as shown

**Comment by xla** [comment]
@jezsmith720 That's surprising as we have it running in that setup on multiple peoples machines. Which node version are you rocking?

**Pull request merged**
