### PR TITLE
stubs out some changes to the app

### PR DESCRIPTION
**Pull request by owocki**
stubs out some changes to the app

screencapture-localhost-3000-2019-11-04-14_38_29

still todo: 
- full logo
- start stubbing out rough agenda with commits we have so far
- add FAQ/ registration links
- what else?

### CODE REVIEW

**Comment by owocki** [comment]
how do we deploy? https://web3.sustainoss.org/

**Comment by xla** [comment]
@owocki Hej, check the [section](https://github.com/monadic-xyz/web3#deploy) in the README and lemme know if you run into trouble.

**Comment by owocki** [comment]
@xla i see the commands, i just dont have access to the server to actually run them!

**Comment by abbey-titcomb** [comment]
Owocki - I’ll deploy once I push my newest changes !

**Comment by xla** [comment]
@owocki You can run it from inside the repository, there is no server involved.

**Comment by xla** [comment]
@owocki Only thing to note is you need to run it form the OG `monadic-xyz/web3` and not a fork.

**Pull request merged**
